# Generated by Django 3.2 on 2022-05-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_auto_20220503_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='course', to='qbank.Topic'),
        ),
    ]
