# Generated by Django 3.2 on 2022-05-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0005_section_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answerChoiceList',
            field=models.ManyToManyField(blank=True, to='qbank.Answer'),
        ),
    ]
